using System.Text;
using System.Text.Json;

namespace HireMindsAPI.Services
{
    public class AIFeedbackService
    {
        private readonly HttpClient _httpClient;
        private readonly string _apiKey;
        private readonly string _model;

        public AIFeedbackService(HttpClient httpClient, IConfiguration config)
        {
            _httpClient = httpClient;
            // Read API key and model from appsettings.json
            _apiKey = config["Gemini:ApiKey"]!;
            _model = config["Gemini:Model"] ?? "gemini-1.5-flash";
        }

        // ==================== CALL GEMINI TO GET FEEDBACK ====================
        public async Task<string> GetFeedbackAsync(string jobTitle, int score, int total, List<string> strongTopics, List<string> weakTopics)
        {
            try
            {
                // 1. Prepare the prompt to send to Gemini
                string strong = strongTopics.Any() ? string.Join(", ", strongTopics) : "None specifically";
                string weak = weakTopics.Any() ? string.Join(", ", weakTopics) : "None specifically";

                string prompt = $@"
You are an expert technical interviewer giving feedback to a candidate.
They applied for: {jobTitle}
They scored: {score} out of {total} in the technical MCQ test.
Their strong topics were: {strong}.
Their weak topics were: {weak}.

Provide short, encouraging feedback strictly in these 3 parts:
✅ What you did well:
⚠️ Where to improve:
📋 Action plan: (2 bullet points)

Keep it very concise, professional, and under 100 words total.";

                // 2. Build the request body expected by Gemini API
                var requestBody = new
                {
                    contents = new[]
                    {
                        new
                        {
                            parts = new[]
                            {
                                new { text = prompt }
                            }
                        }
                    }
                };

                // Convert object to JSON
                var jsonContent = new StringContent(JsonSerializer.Serialize(requestBody), Encoding.UTF8, "application/json");

                // 3. Make the API call to Google Gemini
                string url = $"https://generativelanguage.googleapis.com/v1beta/models/{_model}:generateContent?key={_apiKey}";
                
                var response = await _httpClient.PostAsync(url, jsonContent);
                response.EnsureSuccessStatusCode(); // Throws if not 200 OK

                // 4. Parse the response
                var responseString = await response.Content.ReadAsStringAsync();
                var geminiResponse = JsonSerializer.Deserialize<GeminiResponse>(responseString, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                // Extract and return the actual text generated by Gemini
                if (geminiResponse != null && geminiResponse.Candidates != null && geminiResponse.Candidates.Count > 0)
                {
                    return geminiResponse.Candidates[0].Content.Parts[0].Text;
                }

                return "Feedback generated successfully, but the format was unexpected.";
            }
            catch (Exception ex)
            {
                // Log error to console for debugging
                Console.WriteLine($"[AI FEEDBACK ERROR]: {ex.Message}");

                // Provide a robust rule-based fallback so the user sees meaningful feedback even if API fails
                return GenerateFallbackFeedback(score, total, strongTopics, weakTopics);
            }
        }

        private string GenerateFallbackFeedback(int score, int total, List<string> strong, List<string> weak)
        {
            double percentage = (double)score / total * 100;
            var sb = new StringBuilder();

            // Part 1: What you did well
            sb.AppendLine("✅ What you did well:");
            if (percentage >= 80)
                sb.AppendLine("- Excellent overall performance! Your technical foundation is very strong.");
            else if (strong.Any())
                sb.AppendLine($"- You demonstrated good understanding of {string.Join(" and ", strong.Take(2))}.");
            else
                sb.AppendLine("- You have a good start on the core concepts of this role.");

            sb.AppendLine();

            // Part 2: Where to improve
            sb.AppendLine("⚠️ Where to improve:");
            if (weak.Any())
                sb.AppendLine($"- Focus on deepening your knowledge in {string.Join(" and ", weak.Take(2))}.");
            else if (percentage < 50)
                sb.AppendLine("- Review the fundamental principles and spend more time on hands-on practice.");
            else
                sb.AppendLine("- Keep polishing your advanced skills to reach the next level of expertise.");

            sb.AppendLine();

            // Part 3: Action plan
            sb.AppendLine("📋 Action plan:");
            if (weak.Any())
                sb.AppendLine($"- Take a dedicated course or read documentation on {weak.First()}.");
            else
                sb.AppendLine("- Build a small project to apply your existing knowledge.");
            
            sb.AppendLine("- Practice more MCQ-style assessments to improve speed and accuracy.");

            return sb.ToString();
        }
    }

    // ==================== MODELS TO PARSE GEMINI JSON RESPONSE ====================
    
    public class GeminiResponse
    {
        public List<GeminiCandidate> Candidates { get; set; } = new();
    }

    public class GeminiCandidate
    {
        public GeminiContent Content { get; set; } = new();
    }

    public class GeminiContent
    {
        public List<GeminiPart> Parts { get; set; } = new();
    }

    public class GeminiPart
    {
        public string Text { get; set; } = string.Empty;
    }
}
